package task_1.Exceptions;

public class NameAlreadyExsist extends Exception{
}
